split long lines
In addition to causing overly long lines, this use of logical
expressions for flow control is bad style.

diff --git a/suse_openstack_cloud b/suse_openstack_cloud
--- a/suse_openstack_cloud
+++ b/suse_openstack_cloud
@@ -12,7 +12,12 @@ SVER=1.0.0
 RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
 LOG_LINES=5000  # 0 means include the entire file
 
-[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }
+if [ -s $RCFILE ]; then
+    if ! source $RCFILE; then
+        echo "ERROR: Initializing resource file: $RCFILE" >&2
+        exit 1
+    fi
+fi
 
 validate_rpm_if_installed() {
     thisrpm="$1"
